site_name: UoB GDS Workshops
site_description: Workshops and resources for the University of Bristol Game Development & Design Society
repo_url: https://github.com/Zingawawoo/GDD-Repo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - def_list
  - attr_list
nav:
  - Home: index.md
  - Workshops:
        - Unreal Engine: workshops/unreal.md
        - Unity: workshops/unity.md
        - Godot: workshops/2025-01-intro-to-godot.md   # keep or replace with a category page
        - Blender: workshops/blender.md
  - Events: events.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/placeholder
    - icon: fontawesome/brands/github
      link: https://github.com/your-org
