site_name: UoB GDS Workshops
site_description: Workshops and resources for the University of Bristol Game Development & Design Society
repo_url: https://github.com/your-org/your-repo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - def_list
  - attr_list
nav:
  - Home: index.md
  - Workshops:
      - Intro to Godot (Jan 2025): workshops/2025-01-intro-to-godot.md
      - Pixel Art Basics (Feb 2025): workshops/2025-02-pixel-art-basics.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/placeholder
    - icon: fontawesome/brands/github
      link: https://github.com/your-org
